### PR TITLE
Update ad dsynth documentation

### PR DESCRIPTION
**Pull request by chrisanthropic**
Hi folks,

Here's my first pass at updating the ADDsynth documentation.
I relied primarily on these sources:
- https://github.com/zynaddsubfx/zynaddsubfx/tree/master/doc
- https://wiki.linuxaudio.org/wiki/zynaddsubfx_manual
- goals document in this repo

I tried to keep to the basic format and tone of the existing docs in this repo.

### CODE REVIEW

**Comment by pdesaulniers** [comment]
A lot of the info presented here is not actually specific to ADDsynth. SUBsynth and PADsynth have envelopes and LFOs too. Perhaps @fundamental has something in mind for handling this?

**Comment by chrisanthropic** [comment]
Yeah, I thought that might be the case. Perhaps it would be better to break it out into "modules" like Unfa did with the Oscillator stuff. 

Then we could link to it?

**Comment by fundamental** [comment]
Thanks for taking the time to port over some of the information from pre-existing docs. As a general organizational note, one of the major goals of this user manual is to provide more of a focus on the "How?" and the "Why?". So, for something like an envelope I would say it makes sense to talk about it independently some and talk about it differently in an integrated sense as well. 

Consider a user asking "How do I make my drum sounds more aggressive?" Then that would be a motivating prompt for talking about changing the attack and using some of the punch functionality. Along those same lines a user might as "Why would I use the frequency envelope? it sounds weird". The older docs focus more on the "What?" question which explains the smaller details such as "What does knob A.dt do?" rather than providing the big picture. So, in general don't worry about getting too detailed coverage on the "What", but try to use the previously documented "What" to establish "Why" something is useful and "How" a user can benefit from some functionality.

Hopefully that makes sense.

**Comment by fundamental** [comment]
Just to double check based upon comments in #16, should this PR be considered a work in progress? (I'm fine either way, though I'll hold off on merging if you wanted to make additional changes before merging)

**Comment by chrisanthropic** [comment]
I'm fine with you merging it if you find it useful in it's current state but I won't be offended if it's not the type of docs you wanted and you'd rather close this PR. 

Either decision is fine by me.

**Comment by fundamental** [comment]
Thanks for the contribution :+1:

**Pull request merged**
