### PR TITLE
Adds intro tutorials: kick drum synthesis, snare synthesis, hi-hat synthesis

### PR DESCRIPTION
**Pull request by chrisanthropic**
Hi again,

Here's the follow-up to the QuickStart guide I wrote.

Now that I've got it done, I'd like to discuss my thoughts on documentation moving forward.
Most of these docs are coming from my own desire to learn Zyn-Fusion. 

As a quick background - I've only been playing with synths and audio for a few months so I'm very much a beginner. 

I'm approaching this like I do most of my linux projects which is to build an understanding from the ground up.

I know that Unfa has started a `Sawtooth` tutorial to go after the quick-start, but I must admit that I don't know what that is or _why_ I would want to do that.

What _I_ *do* want to do is create my own drumkit.

Since I plan on documenting for myself, I'd love to keep contributing but I want to ensure I'm giving y'all what you actually want/need. 

My plan is to continue to create the following documentation:

[x] QuickStart
[x] Kick Drum
[x] Snare Drum
[x] Hi-Hat

Then ideally 
[ ] Strings ?
[ ] Bass
[ ] Clap/Bell/Secondary percussion

For me, this would complete the `Intro` section, having walked through creating a simple drum kit, a few supporting instruments, brief introductions to LFOs, envelopes, and filters, multiple voices, and using Ardour to put it all together to create a very simple track.

I'd expect the next section to dig in deeper about how things like the LFOs, envelopes, and filters work and when you'd use them. If I make it this far in the docs, I'd like to use this section to fine-tune each of the instruments created in the previous step.

I think I'd expect things like math, underlying formulas, etc. to be in the Advanced section.

Anyhow, that's my thoughts and motivations here as a newbie. I hope this is useful to others.

### CODE REVIEW

**Comment by fundamental** [comment]
> I know that Unfa has started a Sawtooth tutorial to go after the quick-start, but I must admit that I don't know what that is or why I would want to do that.

I was the one to put that idea out there as it seemed like a quick way to introduce the add synth oscillator which is a powerful starting place for synthesis (also I think supersaws sound quite nice for how simple they are). As long as there's an alternative which introduces the major concepts at a reasonable pace, then I'm fine with it getting swapped out for something else.

> I've only been playing with synths and audio for a few months so I'm very much a beginner.

Excellent. This means you have the "well, that was initially confusing" feeling lurking in the back of your mind. Being able to recall that is very helpful in writing documentation as it helps shift the focus onto highlighting pain points.

> I hope this is useful to others.

Looking through the current progress it looks like it maintains the idea of well paced learning goals from each module, so it's looking great :+1:

**Comment by chrisanthropic** [comment]
Oh, thanks!

I'm nearly finished with the hi-hat tutorial so I'll be pushing that to the tail end of this PR shortly.

**Comment by chrisanthropic** [comment]
@fundamental - I just pushed the hi-hat tutorial so I'm done messing with this PR.

I've tried to lessen the guidance with each lesson as they progress. Meaning that the first one has screenshots and hand-holding for *everything*. The second and third only show screenshots for things not covered previously.

Let me know if there's any questions or changes needed.

**Comment by fundamental** [comment]
Looks good for the time being. For the other ideas you mention it might be good to integrate them with somewhat more advance sound design targeting a particular synth engine later in the manual. That should help specialize the goals now that the intro modules are covered.

**Pull request merged**
